# Generated by Django 5.2.8 on 2025-11-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_mytask'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemPromts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('name_classification', 'Классификация имени')], max_length=64)),
                ('promt', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
