# Generated by Django 5.2.8 on 2025-11-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_systempromts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systempromts',
            name='promt',
            field=models.TextField(blank=True),
        ),
    ]
