# Generated by Django 5.2.8 on 2025-11-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_systempromts_promt'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteproject',
            name='promt',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siteproject',
            name='ref_site_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='systempromts',
            name='type',
            field=models.CharField(choices=[('name_classification', 'Классификация имени сайта')], max_length=64),
        ),
    ]
