# Generated by Django 5.2.8 on 2025-11-17 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_siteproject_promt_siteproject_ref_site_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteproject',
            name='type',
            field=models.CharField(choices=[('generate_name', 'Генерация имени'), ('generate_site', 'Генерация сайта')], default=None, max_length=20),
            preserve_default=False,
        ),
    ]
