# Generated by Django 5.2.8 on 2025-11-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_siteproject_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteproject',
            name='type',
        ),
        migrations.AddField(
            model_name='mytask',
            name='type',
            field=models.CharField(choices=[('generate_name', 'Генерация имени'), ('generate_site', 'Генерация сайта')], default=None, max_length=20),
            preserve_default=False,
        ),
    ]
