# Generated by Django 5.2.8 on 2025-11-17 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_siteproject_type_mytask_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytask',
            name='site_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='task', to='core.siteproject'),
            preserve_default=False,
        ),
    ]
