# Generated by Django 5.2.8 on 2025-11-17 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_mytask_site_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mytask',
            old_name='site_id',
            new_name='site',
        ),
        migrations.RemoveField(
            model_name='mytask',
            name='task_id',
        ),
    ]
