# Generated by Django 5.2.8 on 2025-11-17 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_site_id_mytask_site_remove_mytask_task_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mytask',
            name='user',
        ),
    ]
