# Generated by Django 5.2.8 on 2025-11-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_mytask_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteproject',
            name='status',
            field=models.CharField(choices=[('awaiting', 'Ожидает'), ('processing', 'Выполняется'), ('done', 'Готов'), ('error', 'Ошибка'), ('archived', 'Архив')], default='awaiting', max_length=20),
        ),
    ]
