# Generated by Django 5.2.8 on 2025-11-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_siteproject_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systempromts',
            name='type',
            field=models.CharField(choices=[('basic_promt', 'Базовый промт'), ('name_classification', 'Классификация имени сайта')], max_length=64),
        ),
    ]
