# Generated by Django 5.2.8 on 2025-11-17 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_systempromts_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AICommunicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_model', models.CharField(max_length=20)),
                ('promt', models.TextField()),
                ('answer', models.TextField()),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='log', to='core.siteproject')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='log', to='core.mytask')),
            ],
        ),
    ]
