# Generated by Django 5.2.8 on 2025-11-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_aicommunicationlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aicommunicationlog',
            name='site',
        ),
        migrations.AddField(
            model_name='aicommunicationlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aicommunicationlog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='aicommunicationlog',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
