# Generated by Django 5.2.8 on 2025-11-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_aicommunicationlog_site_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CHATGPT', 'CHATGPT'), ('DEEPSEEK', 'DEEPSEEK')], max_length=20)),
                ('model', models.CharField(choices=[('gpt-5', 'gpt-5'), ('gpt-5.1', 'gpt-5.1')], max_length=20)),
                ('promt_tokens_price_1m', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('completion_tokens_price_1m', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ],
            options={
                'unique_together': {('type', 'model')},
            },
        ),
    ]
