# Generated by Django 5.2.8 on 2025-11-18 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_aimodelssettings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aimodelssettings',
            old_name='promt_tokens_price_1m',
            new_name='prompt_tokens_price_1m',
        ),
    ]
