# Generated by Django 5.2.8 on 2025-11-18 12:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_rename_promt_tokens_price_1m_aimodelssettings_prompt_tokens_price_1m'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodelssettings',
            name='my_margin',
            field=models.FloatField(default=2, validators=[django.core.validators.MinValueValidator(1.0)]),
        ),
    ]
