# Generated by Django 5.2.8 on 2025-11-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_aimodelssettings_my_margin'),
    ]

    operations = [
        migrations.AddField(
            model_name='aicommunicationlog',
            name='ai_type',
            field=models.CharField(blank=True, choices=[('CHATGPT', 'CHATGPT'), ('DEEPSEEK', 'DEEPSEEK')], default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='aicommunicationlog',
            name='completion_tokens_price_1m',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='aicommunicationlog',
            name='price_for_ai',
            field=models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='aicommunicationlog',
            name='price_for_client',
            field=models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='aicommunicationlog',
            name='prompt_tokens_price_1m',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='aicommunicationlog',
            name='ai_model',
            field=models.CharField(blank=True, choices=[('gpt-5', 'gpt-5'), ('gpt-5.1', 'gpt-5.1')], default=None, max_length=20, null=True),
        ),
    ]
