# Generated by Django 5.2.8 on 2025-11-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_aicommunicationlog_ai_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aicommunicationlog',
            name='completion_tokens_price_1m',
        ),
        migrations.RemoveField(
            model_name='aicommunicationlog',
            name='prompt_tokens_price_1m',
        ),
        migrations.AddField(
            model_name='aicommunicationlog',
            name='completion_tokens',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='aicommunicationlog',
            name='prompt_tokens',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
