# Generated by Django 5.2.8 on 2025-11-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_aicommunicationlog_completion_tokens_price_1m_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SystemPromts',
            new_name='SystemPrompts',
        ),
        migrations.RenameField(
            model_name='systemprompts',
            old_name='promt',
            new_name='prompt',
        ),
        migrations.AlterField(
            model_name='aicommunicationlog',
            name='ai_model',
            field=models.CharField(blank=True, choices=[('gpt-5', 'gpt-5'), ('gpt-5.1', 'gpt-5.1'), ('deepseek-chat', 'deepseek-chat'), ('deepseek-reasoner', 'deepseek-reasoner')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='aimodelssettings',
            name='model',
            field=models.CharField(choices=[('gpt-5', 'gpt-5'), ('gpt-5.1', 'gpt-5.1'), ('deepseek-chat', 'deepseek-chat'), ('deepseek-reasoner', 'deepseek-reasoner')], max_length=20),
        ),
    ]
