# Generated by Django 5.2.8 on 2025-11-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_rename_systempromts_systemprompts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemprompts',
            name='type',
            field=models.CharField(choices=[('basic_promt', 'Базовый промт'), ('name_classification', 'Классификация имени сайта'), ('basic_json', 'JSON коммуникация')], max_length=64),
        ),
    ]
