# Generated by Django 5.2.8 on 2025-11-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_systemprompts_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aicommunicationlog',
            old_name='promt',
            new_name='prompt',
        ),
        migrations.RenameField(
            model_name='siteproject',
            old_name='promt',
            new_name='prompt',
        ),
        migrations.AlterField(
            model_name='systemprompts',
            name='type',
            field=models.CharField(choices=[('basic_prompt', 'Базовый промт'), ('name_classification', 'Классификация имени сайта'), ('basic_json', 'JSON коммуникация')], max_length=64),
        ),
    ]
