# Generated by Django 5.2.8 on 2025-11-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_rename_promt_aicommunicationlog_prompt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytask',
            name='data_payload',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
