# Generated by Django 5.2.8 on 2025-11-19 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_mytask_data_payload'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubSiteProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('root_sub_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_site', to='core.subsiteproject')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_site', to='core.siteproject')),
            ],
        ),
    ]
