# Generated by Django 5.2.8 on 2025-11-19 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_subsiteproject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mytask',
            name='site',
        ),
        migrations.AddField(
            model_name='mytask',
            name='sub_site',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='task', to='core.subsiteproject'),
            preserve_default=False,
        ),
    ]
