# Generated by Django 5.2.8 on 2025-11-19 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_mytask_site_mytask_sub_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsiteproject',
            name='dir',
            field=models.CharField(default=None, max_length=64),
            preserve_default=False,
        ),
    ]
