# Generated by Django 5.2.8 on 2025-11-19 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_subsiteproject_dir'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsiteproject',
            name='error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subsiteproject',
            name='status',
            field=models.CharField(choices=[('awaiting', 'Ожидает'), ('processing', 'Выполняется'), ('done', 'Готов'), ('error', 'Ошибка')], default='awaiting', max_length=20),
        ),
        migrations.AlterField(
            model_name='subsiteproject',
            name='root_sub_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_site', to='core.subsiteproject'),
        ),
    ]
