# Generated by Django 5.2.8 on 2025-11-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_subsiteproject_error_subsiteproject_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytask',
            name='status',
            field=models.CharField(choices=[('awaiting', 'Ожидает'), ('processing', 'Выполняется'), ('done', 'Готов'), ('error', 'Ошибка')], default='awaiting', max_length=20),
        ),
    ]
