# Generated by Django 5.2.8 on 2025-11-19 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_mytask_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteproject',
            name='status',
        ),
    ]
