# Generated by Django 5.2.8 on 2025-11-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_remove_siteproject_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteproject',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
