# Generated by Django 5.2.8 on 2025-11-20 05:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_siteproject_is_archived'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='amount',
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount_ai',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount_client',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='sub_site',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='core.subsiteproject'),
        ),
        migrations.AlterField(
            model_name='aicommunicationlog',
            name='ai_model',
            field=models.CharField(blank=True, choices=[('gpt-5', 'gpt-5'), ('gpt-5.1', 'gpt-5.1'), ('gpt-image-1', 'gpt-image-1'), ('deepseek-chat', 'deepseek-chat'), ('deepseek-reasoner', 'deepseek-reasoner')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='aimodelssettings',
            name='model',
            field=models.CharField(choices=[('gpt-5', 'gpt-5'), ('gpt-5.1', 'gpt-5.1'), ('gpt-image-1', 'gpt-image-1'), ('deepseek-chat', 'deepseek-chat'), ('deepseek-reasoner', 'deepseek-reasoner')], max_length=20),
        ),
        migrations.AlterField(
            model_name='mytask',
            name='type',
            field=models.CharField(choices=[('generate_name', 'Генерация имени'), ('generate_site', 'Генерация сайта'), ('generate_image', 'Генерация изображения')], max_length=20),
        ),
        migrations.AlterField(
            model_name='systemprompts',
            name='type',
            field=models.CharField(choices=[('basic_prompt', 'Базовый промт'), ('name_classification', 'Классификация имени сайта'), ('basic_json', 'JSON коммуникация'), ('generate_image_for_site', 'Генерация картинки для сайта'), ('i_have_page_screenshot', 'У меня есть скриншот картинки')], max_length=64),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
