# Generated by Django 5.2.8 on 2025-11-20 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_remove_transaction_amount_transaction_amount_ai_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsiteproject',
            name='status',
        ),
    ]
