# Generated by Django 5.2.8 on 2025-11-20 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_remove_subsiteproject_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='balance',
        ),
        migrations.CreateModel(
            name='ImageAIEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=256)),
                ('sub_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_ai', to='core.subsiteproject')),
            ],
            options={
                'unique_together': {('sub_site', 'file_path')},
            },
        ),
        migrations.CreateModel(
            name='ImageAIEditConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('image_ai_edit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_ai', to='core.imageaiedit')),
            ],
        ),
    ]
