# Generated by Django 5.2.8 on 2025-11-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_remove_profile_balance_imageaiedit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageaieditconversation',
            name='answer_id',
            field=models.CharField(default=None, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imageaieditconversation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imageaieditconversation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
