# Generated by Django 5.2.8 on 2025-11-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_imageaieditconversation_answer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageaieditconversation',
            name='comment',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imageaieditconversation',
            name='status',
            field=models.CharField(choices=[('awaiting', 'Ожидает'), ('processing', 'Выполняется'), ('done', 'Готов'), ('error', 'Ошибка')], default='awaiting', max_length=20),
        ),
    ]
