# Generated by Django 5.2.8 on 2025-11-20 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_imageaieditconversation_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageaieditconversation',
            name='status',
        ),
        migrations.AddField(
            model_name='imageaieditconversation',
            name='task',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='image_ai', to='core.mytask'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mytask',
            name='type',
            field=models.CharField(choices=[('generate_name', 'Генерация имени'), ('generate_site', 'Генерация сайта'), ('generate_image', 'Генерация изображения'), ('edit_image', 'Редактирование изображения')], max_length=20),
        ),
    ]
