# Generated by Django 5.2.8 on 2025-11-20 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_remove_imageaieditconversation_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageaieditconversation',
            name='image_ai_edit',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_ai', to='core.imageaiedit'),
        ),
    ]
