# Generated by Django 5.2.8 on 2025-11-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_imageaieditconversation_image_ai_edit'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodelssettings',
            name='format',
            field=models.CharField(choices=[('text', 'text'), ('image', 'image')], default=None, max_length=20),
            preserve_default=False,
        ),
    ]
