# Generated by Django 5.2.8 on 2025-11-20 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_mytask_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytask',
            name='type',
            field=models.CharField(choices=[('generate_name', 'Генерация имени'), ('generate_site', 'Генерация сайта'), ('generate_image', 'Генерация изображения'), ('edit_image', 'Редактирование изображения'), ('edit_site', 'Редактирование сайта'), ('edit_file', 'Редактирование файла')], max_length=20),
        ),
    ]
