# Generated by Django 5.2.8 on 2025-11-21 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_alter_mytask_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aicommunicationlog',
            name='ai_model',
            field=models.CharField(blank=True, choices=[('gpt-5', 'gpt-5'), ('gpt-5.1', 'gpt-5.1'), ('gpt-4o', 'gpt-4o'), ('gpt-image-1', 'gpt-image-1'), ('deepseek-chat', 'deepseek-chat'), ('deepseek-reasoner', 'deepseek-reasoner')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='aimodelssettings',
            name='model',
            field=models.CharField(choices=[('gpt-5', 'gpt-5'), ('gpt-5.1', 'gpt-5.1'), ('gpt-4o', 'gpt-4o'), ('gpt-image-1', 'gpt-image-1'), ('deepseek-chat', 'deepseek-chat'), ('deepseek-reasoner', 'deepseek-reasoner')], max_length=20),
        ),
    ]
