# Generated by Django 5.2.8 on 2025-11-21 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_aicommunicationlog_ai_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemprompts',
            name='type',
            field=models.CharField(choices=[('basic_prompt', 'Базовый промт'), ('name_classification', 'Классификация имени сайта'), ('basic_json', 'JSON коммуникация'), ('generate_image_for_site', 'Генерация картинки для сайта'), ('i_have_page_screenshot', 'У меня есть скриншот картинки'), ('site_edit_make_plan', 'Создание плана редактирования сайта'), ('site_copy', 'Копирование сайта')], max_length=64),
        ),
    ]
