# Generated by Django 5.2.8 on 2025-11-21 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_alter_systemprompts_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aicommunicationlog',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log', to='core.mytask'),
        ),
    ]
