# Generated by Django 5.2.8 on 2025-11-26 12:23

import uuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_aicommunicationlog_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TopUpRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('awaiting', 'awaiting'), ('done', 'done'), ('error', 'error')], max_length=10)),
                ('provider', models.CharField(choices=[('cryptogator', 'cryptogator')], max_length=16)),
                ('method', models.CharField(choices=[('Tron', 'Tron'), ('Ethereum', 'Ethereum')], max_length=10)),
                ('currency', models.CharField(choices=[('USDT', 'USDT')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=10)),
                ('wallet_to_pay_address', models.CharField(blank=True, max_length=255)),
                ('expired_at', models.DateTimeField()),
                ('amount_min_for_order', models.DecimalField(decimal_places=6, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topup_request', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
