# Generated by Django 5.2.8 on 2025-11-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_topuprequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topuprequest',
            name='amount',
        ),
        migrations.AlterField(
            model_name='topuprequest',
            name='wallet_to_pay_address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
