# Generated by Django 5.2.8 on 2025-11-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_remove_topuprequest_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topuprequest',
            name='amount_min_for_order',
            field=models.DecimalField(decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='topuprequest',
            name='expired_at',
            field=models.DateTimeField(null=True),
        ),
    ]
