# Generated by Django 5.2.8 on 2025-11-26 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_alter_topuprequest_amount_min_for_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topuprequest',
            name='comission',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='topuprequest',
            name='payment_gateway_transaction_id',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
