# Generated by Django 5.2.8 on 2025-11-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_topuprequest_comission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGatewaySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('cryptogator', 'cryptogator')], max_length=20)),
                ('commission_extra', models.FloatField()),
            ],
        ),
    ]
