# Generated by Django 5.2.8 on 2025-11-26 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_paymentgatewaysettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topuprequest',
            name='comission',
        ),
    ]
