# Generated by Django 5.2.8 on 2025-11-27 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_remove_topuprequest_comission'),
    ]

    operations = [
        migrations.AddField(
            model_name='topuprequest',
            name='blockchain_trx_id',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='topuprequest',
            name='topup_transcation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='topup_request', to='core.transaction'),
        ),
    ]
