# Generated by Django 5.2.8 on 2025-11-27 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_topuprequest_blockchain_trx_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topuprequest',
            old_name='topup_transcation',
            new_name='topup_transaction',
        ),
    ]
