# Generated by Django 5.2.8 on 2025-11-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_rename_topup_transcation_topuprequest_topup_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='topuprequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
