# Generated by Django 5.2.8 on 2025-11-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_topuprequest_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentgatewaysettings',
            name='currency',
            field=models.CharField(choices=[('USDT', 'USDT')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='paymentgatewaysettings',
            name='method',
            field=models.CharField(choices=[('Tron', 'Tron'), ('Ethereum', 'Ethereum')], max_length=20, null=True),
        ),
    ]
