# Generated by Django 5.2.8 on 2025-11-27 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_paymentgatewaysettings_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentgatewaysettings',
            name='currency',
            field=models.CharField(choices=[('USDT', 'USDT')], max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentgatewaysettings',
            name='method',
            field=models.CharField(choices=[('Tron', 'Tron'), ('Ethereum', 'Ethereum')], default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='paymentgatewaysettings',
            unique_together={('type', 'method', 'currency')},
        ),
    ]
