# Generated by Django 5.2.8 on 2025-11-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_alter_paymentgatewaysettings_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentgatewaysettings',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
