# Generated by Django 5.2.8 on 2025-11-27 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_paymentgatewaysettings_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='topuprequest',
            name='payment_gateway_settings',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='topup_request', to='core.paymentgatewaysettings'),
            preserve_default=False,
        ),
    ]
