# Generated by Django 5.2.8 on 2025-11-27 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_topuprequest_payment_gateway_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topuprequest',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='topuprequest',
            name='method',
        ),
        migrations.RemoveField(
            model_name='topuprequest',
            name='provider',
        ),
    ]
