# Generated by Django 5.2.8 on 2025-12-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_remove_topuprequest_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytask',
            name='errors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mytask',
            name='type',
            field=models.CharField(choices=[('generate_name', 'Генерация имени'), ('generate_site', 'Генерация сайта'), ('copy_site_by_url', 'Копирование сайта по URL-у'), ('generate_image', 'Генерация изображения'), ('edit_image', 'Редактирование изображения'), ('edit_site', 'Редактирование сайта'), ('edit_file', 'Редактирование файла')], max_length=20),
        ),
    ]
