# Generated by Django 5.2.8 on 2025-12-23 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_mytask_errors_alter_mytask_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aicommunicationlog',
            old_name='ai_type',
            new_name='ai_engine',
        ),
        migrations.RenameField(
            model_name='aimodelssettings',
            old_name='type',
            new_name='engine',
        ),
        migrations.AlterUniqueTogether(
            name='aimodelssettings',
            unique_together={('engine', 'model')},
        ),
    ]
