# Generated by Django 5.2.8 on 2025-12-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_rename_ai_type_aicommunicationlog_ai_engine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytask',
            name='ai_engine_config',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
