# Generated by Django 5.2.8 on 2025-12-24 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_mytask_ai_engine_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topuprequest',
            name='amount_min_for_order',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='topuprequest',
            name='blockchain_trx_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='topuprequest',
            name='expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='topuprequest',
            name='payment_gateway_transaction_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='topuprequest',
            name='topup_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='topup_request', to='core.transaction'),
        ),
        migrations.AlterField(
            model_name='topuprequest',
            name='wallet_to_pay_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
