# Generated by Django 5.2.8 on 2025-12-24 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_alter_topuprequest_amount_min_for_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='topup_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='core.topuprequest'),
        ),
        migrations.AlterField(
            model_name='topuprequest',
            name='topup_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='topup_transaction_link', to='core.transaction'),
        ),
    ]
